project:
  type: website

website:
  title: "Git for librarians"
  sidebar:
    style: "docked"
    search: true
    contents:
      - Setup_and_instructions.qmd
      - section: "Getting to know git and Github"
        contents:
          - What_is_git.qmd
      - section: "Github desktop"
        contents:
          - Desktop.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



editor: visual

