project:
  type: website

website:
  title: "Git for librarians"
  sidebar:
    style: "docked"
    search: true
    contents:
      - Setup_and_instructions.qmd
      - section: "Getting to know Git(hub)"
        contents:
          - What_is_git.qmd
          - Git_Github_Gitlab.qmd
          - The_history.qmd
      - section: "Github online"
        contents:
          - Git_online.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



editor: visual

